package com.sb.factorium;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Describes a factory grouping many generators with the same output type.
 * Generator methods that do not specify the generator to use should use the factory's default generator.
 * @param <K> the key type used for this factory's map.
 * @param <T> the type generated by this factory.
 */
public interface IFactory<K, T> extends Generator<T> {

    Generator<T> getDefaultGenerator();

    /**
     * Return all the registered generators.
     * @return
     */
    Map<K, Generator<T>> getGenerators();
}
